// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: api/delivery.proto

package deliverypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeliveryStatus int32

const (
	DeliveryStatus_DELIVERY_STATUS_UNSPECIFIED DeliveryStatus = 0
	DeliveryStatus_DELIVERY_STATUS_CREATED     DeliveryStatus = 1
	DeliveryStatus_DELIVERY_STATUS_PICKED_UP   DeliveryStatus = 2
	DeliveryStatus_DELIVERY_STATUS_IN_TRANSIT  DeliveryStatus = 3
	DeliveryStatus_DELIVERY_STATUS_DELIVERED   DeliveryStatus = 4
)

// Enum value maps for DeliveryStatus.
var (
	DeliveryStatus_name = map[int32]string{
		0: "DELIVERY_STATUS_UNSPECIFIED",
		1: "DELIVERY_STATUS_CREATED",
		2: "DELIVERY_STATUS_PICKED_UP",
		3: "DELIVERY_STATUS_IN_TRANSIT",
		4: "DELIVERY_STATUS_DELIVERED",
	}
	DeliveryStatus_value = map[string]int32{
		"DELIVERY_STATUS_UNSPECIFIED": 0,
		"DELIVERY_STATUS_CREATED":     1,
		"DELIVERY_STATUS_PICKED_UP":   2,
		"DELIVERY_STATUS_IN_TRANSIT":  3,
		"DELIVERY_STATUS_DELIVERED":   4,
	}
)

func (x DeliveryStatus) Enum() *DeliveryStatus {
	p := new(DeliveryStatus)
	*p = x
	return p
}

func (x DeliveryStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeliveryStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_delivery_proto_enumTypes[0].Descriptor()
}

func (DeliveryStatus) Type() protoreflect.EnumType {
	return &file_api_delivery_proto_enumTypes[0]
}

func (x DeliveryStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeliveryStatus.Descriptor instead.
func (DeliveryStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_delivery_proto_rawDescGZIP(), []int{0}
}

type CreateDeliveryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDeliveryRequest) Reset() {
	*x = CreateDeliveryRequest{}
	mi := &file_api_delivery_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDeliveryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDeliveryRequest) ProtoMessage() {}

func (x *CreateDeliveryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_delivery_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDeliveryRequest.ProtoReflect.Descriptor instead.
func (*CreateDeliveryRequest) Descriptor() ([]byte, []int) {
	return file_api_delivery_proto_rawDescGZIP(), []int{0}
}

func (x *CreateDeliveryRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type GetDeliveryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeliveryRequest) Reset() {
	*x = GetDeliveryRequest{}
	mi := &file_api_delivery_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeliveryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeliveryRequest) ProtoMessage() {}

func (x *GetDeliveryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_delivery_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeliveryRequest.ProtoReflect.Descriptor instead.
func (*GetDeliveryRequest) Descriptor() ([]byte, []int) {
	return file_api_delivery_proto_rawDescGZIP(), []int{1}
}

func (x *GetDeliveryRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateDeliveryStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        DeliveryStatus         `protobuf:"varint,2,opt,name=status,proto3,enum=delivery.DeliveryStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDeliveryStatusRequest) Reset() {
	*x = UpdateDeliveryStatusRequest{}
	mi := &file_api_delivery_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDeliveryStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDeliveryStatusRequest) ProtoMessage() {}

func (x *UpdateDeliveryStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_delivery_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDeliveryStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateDeliveryStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_delivery_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateDeliveryStatusRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateDeliveryStatusRequest) GetStatus() DeliveryStatus {
	if x != nil {
		return x.Status
	}
	return DeliveryStatus_DELIVERY_STATUS_UNSPECIFIED
}

type ListDeliveryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDeliveryRequest) Reset() {
	*x = ListDeliveryRequest{}
	mi := &file_api_delivery_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDeliveryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDeliveryRequest) ProtoMessage() {}

func (x *ListDeliveryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_delivery_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDeliveryRequest.ProtoReflect.Descriptor instead.
func (*ListDeliveryRequest) Descriptor() ([]byte, []int) {
	return file_api_delivery_proto_rawDescGZIP(), []int{3}
}

type Delivery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Status        DeliveryStatus         `protobuf:"varint,3,opt,name=status,proto3,enum=delivery.DeliveryStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Delivery) Reset() {
	*x = Delivery{}
	mi := &file_api_delivery_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Delivery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Delivery) ProtoMessage() {}

func (x *Delivery) ProtoReflect() protoreflect.Message {
	mi := &file_api_delivery_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Delivery.ProtoReflect.Descriptor instead.
func (*Delivery) Descriptor() ([]byte, []int) {
	return file_api_delivery_proto_rawDescGZIP(), []int{4}
}

func (x *Delivery) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Delivery) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Delivery) GetStatus() DeliveryStatus {
	if x != nil {
		return x.Status
	}
	return DeliveryStatus_DELIVERY_STATUS_UNSPECIFIED
}

type LocationPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeliveryId    int64                  `protobuf:"varint,1,opt,name=delivery_id,json=deliveryId,proto3" json:"delivery_id,omitempty"`
	Latitude      float64                `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocationPoint) Reset() {
	*x = LocationPoint{}
	mi := &file_api_delivery_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocationPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocationPoint) ProtoMessage() {}

func (x *LocationPoint) ProtoReflect() protoreflect.Message {
	mi := &file_api_delivery_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocationPoint.ProtoReflect.Descriptor instead.
func (*LocationPoint) Descriptor() ([]byte, []int) {
	return file_api_delivery_proto_rawDescGZIP(), []int{5}
}

func (x *LocationPoint) GetDeliveryId() int64 {
	if x != nil {
		return x.DeliveryId
	}
	return 0
}

func (x *LocationPoint) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *LocationPoint) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type LocationReport struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DeliveryId     int64                  `protobuf:"varint,1,opt,name=delivery_id,json=deliveryId,proto3" json:"delivery_id,omitempty"`
	PointsReceived int32                  `protobuf:"varint,2,opt,name=points_received,json=pointsReceived,proto3" json:"points_received,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LocationReport) Reset() {
	*x = LocationReport{}
	mi := &file_api_delivery_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocationReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocationReport) ProtoMessage() {}

func (x *LocationReport) ProtoReflect() protoreflect.Message {
	mi := &file_api_delivery_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocationReport.ProtoReflect.Descriptor instead.
func (*LocationReport) Descriptor() ([]byte, []int) {
	return file_api_delivery_proto_rawDescGZIP(), []int{6}
}

func (x *LocationReport) GetDeliveryId() int64 {
	if x != nil {
		return x.DeliveryId
	}
	return 0
}

func (x *LocationReport) GetPointsReceived() int32 {
	if x != nil {
		return x.PointsReceived
	}
	return 0
}

type LocationAck struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DeliveryId     int64                  `protobuf:"varint,1,opt,name=delivery_id,json=deliveryId,proto3" json:"delivery_id,omitempty"`
	AcceptedPoints int32                  `protobuf:"varint,2,opt,name=accepted_points,json=acceptedPoints,proto3" json:"accepted_points,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LocationAck) Reset() {
	*x = LocationAck{}
	mi := &file_api_delivery_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocationAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocationAck) ProtoMessage() {}

func (x *LocationAck) ProtoReflect() protoreflect.Message {
	mi := &file_api_delivery_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocationAck.ProtoReflect.Descriptor instead.
func (*LocationAck) Descriptor() ([]byte, []int) {
	return file_api_delivery_proto_rawDescGZIP(), []int{7}
}

func (x *LocationAck) GetDeliveryId() int64 {
	if x != nil {
		return x.DeliveryId
	}
	return 0
}

func (x *LocationAck) GetAcceptedPoints() int32 {
	if x != nil {
		return x.AcceptedPoints
	}
	return 0
}

var File_api_delivery_proto protoreflect.FileDescriptor

const file_api_delivery_proto_rawDesc = "" +
	"\n" +
	"\x12api/delivery.proto\x12\bdelivery\"1\n" +
	"\x15CreateDeliveryRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"$\n" +
	"\x12GetDeliveryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"_\n" +
	"\x1bUpdateDeliveryStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x120\n" +
	"\x06status\x18\x02 \x01(\x0e2\x18.delivery.DeliveryStatusR\x06status\"\x15\n" +
	"\x13ListDeliveryRequest\"f\n" +
	"\bDelivery\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x120\n" +
	"\x06status\x18\x03 \x01(\x0e2\x18.delivery.DeliveryStatusR\x06status\"j\n" +
	"\rLocationPoint\x12\x1f\n" +
	"\vdelivery_id\x18\x01 \x01(\x03R\n" +
	"deliveryId\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x03 \x01(\x01R\tlongitude\"Z\n" +
	"\x0eLocationReport\x12\x1f\n" +
	"\vdelivery_id\x18\x01 \x01(\x03R\n" +
	"deliveryId\x12'\n" +
	"\x0fpoints_received\x18\x02 \x01(\x05R\x0epointsReceived\"W\n" +
	"\vLocationAck\x12\x1f\n" +
	"\vdelivery_id\x18\x01 \x01(\x03R\n" +
	"deliveryId\x12'\n" +
	"\x0faccepted_points\x18\x02 \x01(\x05R\x0eacceptedPoints*\xac\x01\n" +
	"\x0eDeliveryStatus\x12\x1f\n" +
	"\x1bDELIVERY_STATUS_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17DELIVERY_STATUS_CREATED\x10\x01\x12\x1d\n" +
	"\x19DELIVERY_STATUS_PICKED_UP\x10\x02\x12\x1e\n" +
	"\x1aDELIVERY_STATUS_IN_TRANSIT\x10\x03\x12\x1d\n" +
	"\x19DELIVERY_STATUS_DELIVERED\x10\x042\xbd\x03\n" +
	"\x0fDeliveryService\x12E\n" +
	"\x0eCreateDelivery\x12\x1f.delivery.CreateDeliveryRequest\x1a\x12.delivery.Delivery\x12?\n" +
	"\vGetDelivery\x12\x1c.delivery.GetDeliveryRequest\x1a\x12.delivery.Delivery\x12Q\n" +
	"\x14UpdateDeliveryStatus\x12%.delivery.UpdateDeliveryStatusRequest\x1a\x12.delivery.Delivery\x12C\n" +
	"\fListDelivery\x12\x1d.delivery.ListDeliveryRequest\x1a\x12.delivery.Delivery0\x01\x12E\n" +
	"\x0eReportLocation\x12\x17.delivery.LocationPoint\x1a\x18.delivery.LocationReport(\x01\x12C\n" +
	"\rTrackDelivery\x12\x17.delivery.LocationPoint\x1a\x15.delivery.LocationAck(\x010\x01B5Z3github.com/slanalan1203/courier-flow/api;deliverypbb\x06proto3"

var (
	file_api_delivery_proto_rawDescOnce sync.Once
	file_api_delivery_proto_rawDescData []byte
)

func file_api_delivery_proto_rawDescGZIP() []byte {
	file_api_delivery_proto_rawDescOnce.Do(func() {
		file_api_delivery_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_delivery_proto_rawDesc), len(file_api_delivery_proto_rawDesc)))
	})
	return file_api_delivery_proto_rawDescData
}

var file_api_delivery_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_delivery_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_delivery_proto_goTypes = []any{
	(DeliveryStatus)(0),                 // 0: delivery.DeliveryStatus
	(*CreateDeliveryRequest)(nil),       // 1: delivery.CreateDeliveryRequest
	(*GetDeliveryRequest)(nil),          // 2: delivery.GetDeliveryRequest
	(*UpdateDeliveryStatusRequest)(nil), // 3: delivery.UpdateDeliveryStatusRequest
	(*ListDeliveryRequest)(nil),         // 4: delivery.ListDeliveryRequest
	(*Delivery)(nil),                    // 5: delivery.Delivery
	(*LocationPoint)(nil),               // 6: delivery.LocationPoint
	(*LocationReport)(nil),              // 7: delivery.LocationReport
	(*LocationAck)(nil),                 // 8: delivery.LocationAck
}
var file_api_delivery_proto_depIdxs = []int32{
	0, // 0: delivery.UpdateDeliveryStatusRequest.status:type_name -> delivery.DeliveryStatus
	0, // 1: delivery.Delivery.status:type_name -> delivery.DeliveryStatus
	1, // 2: delivery.DeliveryService.CreateDelivery:input_type -> delivery.CreateDeliveryRequest
	2, // 3: delivery.DeliveryService.GetDelivery:input_type -> delivery.GetDeliveryRequest
	3, // 4: delivery.DeliveryService.UpdateDeliveryStatus:input_type -> delivery.UpdateDeliveryStatusRequest
	4, // 5: delivery.DeliveryService.ListDelivery:input_type -> delivery.ListDeliveryRequest
	6, // 6: delivery.DeliveryService.ReportLocation:input_type -> delivery.LocationPoint
	6, // 7: delivery.DeliveryService.TrackDelivery:input_type -> delivery.LocationPoint
	5, // 8: delivery.DeliveryService.CreateDelivery:output_type -> delivery.Delivery
	5, // 9: delivery.DeliveryService.GetDelivery:output_type -> delivery.Delivery
	5, // 10: delivery.DeliveryService.UpdateDeliveryStatus:output_type -> delivery.Delivery
	5, // 11: delivery.DeliveryService.ListDelivery:output_type -> delivery.Delivery
	7, // 12: delivery.DeliveryService.ReportLocation:output_type -> delivery.LocationReport
	8, // 13: delivery.DeliveryService.TrackDelivery:output_type -> delivery.LocationAck
	8, // [8:14] is the sub-list for method output_type
	2, // [2:8] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_delivery_proto_init() }
func file_api_delivery_proto_init() {
	if File_api_delivery_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_delivery_proto_rawDesc), len(file_api_delivery_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_delivery_proto_goTypes,
		DependencyIndexes: file_api_delivery_proto_depIdxs,
		EnumInfos:         file_api_delivery_proto_enumTypes,
		MessageInfos:      file_api_delivery_proto_msgTypes,
	}.Build()
	File_api_delivery_proto = out.File
	file_api_delivery_proto_goTypes = nil
	file_api_delivery_proto_depIdxs = nil
}
