// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.2
// source: api/delivery.proto

package deliverypb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DeliveryService_CreateDelivery_FullMethodName       = "/delivery.DeliveryService/CreateDelivery"
	DeliveryService_GetDelivery_FullMethodName          = "/delivery.DeliveryService/GetDelivery"
	DeliveryService_UpdateDeliveryStatus_FullMethodName = "/delivery.DeliveryService/UpdateDeliveryStatus"
	DeliveryService_ListDelivery_FullMethodName         = "/delivery.DeliveryService/ListDelivery"
	DeliveryService_ReportLocation_FullMethodName       = "/delivery.DeliveryService/ReportLocation"
	DeliveryService_TrackDelivery_FullMethodName        = "/delivery.DeliveryService/TrackDelivery"
)

// DeliveryServiceClient is the client API for DeliveryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DeliveryServiceClient interface {
	CreateDelivery(ctx context.Context, in *CreateDeliveryRequest, opts ...grpc.CallOption) (*Delivery, error)
	GetDelivery(ctx context.Context, in *GetDeliveryRequest, opts ...grpc.CallOption) (*Delivery, error)
	UpdateDeliveryStatus(ctx context.Context, in *UpdateDeliveryStatusRequest, opts ...grpc.CallOption) (*Delivery, error)
	ListDelivery(ctx context.Context, in *ListDeliveryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Delivery], error)
	ReportLocation(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[LocationPoint, LocationReport], error)
	TrackDelivery(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[LocationPoint, LocationAck], error)
}

type deliveryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDeliveryServiceClient(cc grpc.ClientConnInterface) DeliveryServiceClient {
	return &deliveryServiceClient{cc}
}

func (c *deliveryServiceClient) CreateDelivery(ctx context.Context, in *CreateDeliveryRequest, opts ...grpc.CallOption) (*Delivery, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Delivery)
	err := c.cc.Invoke(ctx, DeliveryService_CreateDelivery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deliveryServiceClient) GetDelivery(ctx context.Context, in *GetDeliveryRequest, opts ...grpc.CallOption) (*Delivery, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Delivery)
	err := c.cc.Invoke(ctx, DeliveryService_GetDelivery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deliveryServiceClient) UpdateDeliveryStatus(ctx context.Context, in *UpdateDeliveryStatusRequest, opts ...grpc.CallOption) (*Delivery, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Delivery)
	err := c.cc.Invoke(ctx, DeliveryService_UpdateDeliveryStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deliveryServiceClient) ListDelivery(ctx context.Context, in *ListDeliveryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Delivery], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DeliveryService_ServiceDesc.Streams[0], DeliveryService_ListDelivery_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ListDeliveryRequest, Delivery]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DeliveryService_ListDeliveryClient = grpc.ServerStreamingClient[Delivery]

func (c *deliveryServiceClient) ReportLocation(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[LocationPoint, LocationReport], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DeliveryService_ServiceDesc.Streams[1], DeliveryService_ReportLocation_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LocationPoint, LocationReport]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DeliveryService_ReportLocationClient = grpc.ClientStreamingClient[LocationPoint, LocationReport]

func (c *deliveryServiceClient) TrackDelivery(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[LocationPoint, LocationAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DeliveryService_ServiceDesc.Streams[2], DeliveryService_TrackDelivery_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LocationPoint, LocationAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DeliveryService_TrackDeliveryClient = grpc.BidiStreamingClient[LocationPoint, LocationAck]

// DeliveryServiceServer is the server API for DeliveryService service.
// All implementations must embed UnimplementedDeliveryServiceServer
// for forward compatibility.
type DeliveryServiceServer interface {
	CreateDelivery(context.Context, *CreateDeliveryRequest) (*Delivery, error)
	GetDelivery(context.Context, *GetDeliveryRequest) (*Delivery, error)
	UpdateDeliveryStatus(context.Context, *UpdateDeliveryStatusRequest) (*Delivery, error)
	ListDelivery(*ListDeliveryRequest, grpc.ServerStreamingServer[Delivery]) error
	ReportLocation(grpc.ClientStreamingServer[LocationPoint, LocationReport]) error
	TrackDelivery(grpc.BidiStreamingServer[LocationPoint, LocationAck]) error
	mustEmbedUnimplementedDeliveryServiceServer()
}

// UnimplementedDeliveryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDeliveryServiceServer struct{}

func (UnimplementedDeliveryServiceServer) CreateDelivery(context.Context, *CreateDeliveryRequest) (*Delivery, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDelivery not implemented")
}
func (UnimplementedDeliveryServiceServer) GetDelivery(context.Context, *GetDeliveryRequest) (*Delivery, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDelivery not implemented")
}
func (UnimplementedDeliveryServiceServer) UpdateDeliveryStatus(context.Context, *UpdateDeliveryStatusRequest) (*Delivery, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateDeliveryStatus not implemented")
}
func (UnimplementedDeliveryServiceServer) ListDelivery(*ListDeliveryRequest, grpc.ServerStreamingServer[Delivery]) error {
	return status.Error(codes.Unimplemented, "method ListDelivery not implemented")
}
func (UnimplementedDeliveryServiceServer) ReportLocation(grpc.ClientStreamingServer[LocationPoint, LocationReport]) error {
	return status.Error(codes.Unimplemented, "method ReportLocation not implemented")
}
func (UnimplementedDeliveryServiceServer) TrackDelivery(grpc.BidiStreamingServer[LocationPoint, LocationAck]) error {
	return status.Error(codes.Unimplemented, "method TrackDelivery not implemented")
}
func (UnimplementedDeliveryServiceServer) mustEmbedUnimplementedDeliveryServiceServer() {}
func (UnimplementedDeliveryServiceServer) testEmbeddedByValue()                         {}

// UnsafeDeliveryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeliveryServiceServer will
// result in compilation errors.
type UnsafeDeliveryServiceServer interface {
	mustEmbedUnimplementedDeliveryServiceServer()
}

func RegisterDeliveryServiceServer(s grpc.ServiceRegistrar, srv DeliveryServiceServer) {
	// If the following call panics, it indicates UnimplementedDeliveryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DeliveryService_ServiceDesc, srv)
}

func _DeliveryService_CreateDelivery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDeliveryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliveryServiceServer).CreateDelivery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeliveryService_CreateDelivery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliveryServiceServer).CreateDelivery(ctx, req.(*CreateDeliveryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeliveryService_GetDelivery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeliveryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliveryServiceServer).GetDelivery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeliveryService_GetDelivery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliveryServiceServer).GetDelivery(ctx, req.(*GetDeliveryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeliveryService_UpdateDeliveryStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDeliveryStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliveryServiceServer).UpdateDeliveryStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeliveryService_UpdateDeliveryStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliveryServiceServer).UpdateDeliveryStatus(ctx, req.(*UpdateDeliveryStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeliveryService_ListDelivery_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListDeliveryRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DeliveryServiceServer).ListDelivery(m, &grpc.GenericServerStream[ListDeliveryRequest, Delivery]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DeliveryService_ListDeliveryServer = grpc.ServerStreamingServer[Delivery]

func _DeliveryService_ReportLocation_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DeliveryServiceServer).ReportLocation(&grpc.GenericServerStream[LocationPoint, LocationReport]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DeliveryService_ReportLocationServer = grpc.ClientStreamingServer[LocationPoint, LocationReport]

func _DeliveryService_TrackDelivery_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DeliveryServiceServer).TrackDelivery(&grpc.GenericServerStream[LocationPoint, LocationAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DeliveryService_TrackDeliveryServer = grpc.BidiStreamingServer[LocationPoint, LocationAck]

// DeliveryService_ServiceDesc is the grpc.ServiceDesc for DeliveryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeliveryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "delivery.DeliveryService",
	HandlerType: (*DeliveryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDelivery",
			Handler:    _DeliveryService_CreateDelivery_Handler,
		},
		{
			MethodName: "GetDelivery",
			Handler:    _DeliveryService_GetDelivery_Handler,
		},
		{
			MethodName: "UpdateDeliveryStatus",
			Handler:    _DeliveryService_UpdateDeliveryStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListDelivery",
			Handler:       _DeliveryService_ListDelivery_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ReportLocation",
			Handler:       _DeliveryService_ReportLocation_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "TrackDelivery",
			Handler:       _DeliveryService_TrackDelivery_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/delivery.proto",
}
